name: Automated Translation Workflow
on: [push]
jobs:
    Translation:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # Currently supported languages - Arabic [ar], Bangladesh [bn], German [de], Spanish [es], Korean [ko]
                lang: [ar, bn, de, es, ko]

        steps:
            - name: 'Source: [${{github.event.workflow_run.head_repository.full_name}}/${{ github.event.workflow_run.head_branch }}]'
              run: echo 'Pushing strings and translations from ${{github.event.workflow_run.head_repository.full_name}}/${{ github.event.workflow_run.head_branch }}'
            - name: Checkout ⬇️
              uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.workflow_run.head_branch }}
                  repository: ${{github.event.workflow_run.head_repository.full_name}}
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '16.x'
            - name: Installing Crowdin
              run: npm i -g @crowdin/cli
            - name: 'Running Automated Translation 🤖 - ${{matrix.lang}}'
            - run: echo 'Translating....'
