name: Push Translation
on:
  workflow_run:
    workflows: ["Pre-push Translation"]
    types:
      - completed
jobs:
    push-translation:
        if: startsWith(github.event.workflow_run.head_branch, 'translation') || startsWith(github.event.workflow_run.head_branch, 'stp')
        runs-on: ubuntu-latest
        steps:
            - name: 'Source: [${{ github.event.workflow_run.head_repository.full_name }}/${{ github.event.workflow_run.head_branch }}]'
              run: echo 'Pushing strings and translations from ${{github.event.workflow_run.head_repository.full_name}}/${{ github.event.workflow_run.head_branch }}'
            - name: Checkout ⬇️
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.workflow_run.head_branch }}
                  repository: ${{ github.event.workflow_run.head_repository.full_name }}
            - name: Setup Node 📦
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: Installing Crowdin 📦
              run: npm i -g @crowdin/cli
            - name: Download and Commit New Translations
              if: github.event.workflow_run.head_commit.message == 'auto-pull-translation'
              run: |
                  crowdin download -b ${{ github.event.workflow_run.head_branch }} -T ${{ secrets.CROWDIN_API_KEY }} && crowdin download -b  ${{ github.event.workflow_run.head_branch }} -l zh-CN -T ${{ secrets.CROWDIN_API_KEY }}
                  if git diff --exit-code; then
                    echo "No new translation data to commit 🫙"
                  else
                    echo "Committing new translation data 📝"
                    echo "Setting up Git identity"
                    git config --global user.name "DerivFE"
                    git config --global user.email "80095553+DerivFE@users.noreply.github.com"
                    git add -u
                    git commit -m "translation: 📚 sync translations from crowdin feature branch"
                    git push origin ${{ github.event.workflow_run.head_branch }}
                  fi
            - name: Pushing Strings & Translations ⬆️
              run: crowdin upload sources -b ${{ github.event.workflow_run.head_branch }} -T ${{ secrets.CROWDIN_API_KEY }}; crowdin upload translations -b ${{ github.event.workflow_run.head_branch }} -T ${{ secrets.CROWDIN_API_KEY }}


